apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: mortgage-app-placement
  namespace: default  
  labels:
    app: mortgage-app-mortgage
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      environment: Dev
