apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ingress-nginx-subscription-green
  namespace: nginx-green
  labels:
    app: nginx-deployment
spec:
  channel: demo/gitops
  placement:
    placementRef:
      name: nginx-deployment
      kind: PlacementRule
