apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-saude-digital
  namespace: demo-saude-digital
  labels:
    app: demo-saude-digital
spec:
  channel: demo-saude-digital-repos/github-redhat-sa-brazil-demo-summitgov-cy20
  placement:
    placementRef:
      name: demo-saude-digital
      kind: PlacementRule
