apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops
  namespace: demo
spec:
  pathname: 'https://github.com/open-cluster-management/demo-subscription-gitops.git'
  type: Git
