apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: nginx-app-details-acmtest-helmrepo
  name: nginx-app-acmtest-helmrepo
  namespace: acmtest-helmrepo-ns-sub
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: nginx-app-details-acmtest-helmrepo
