apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cassandra-app-placement
  namespace: cassandra-app-ns
  labels:
    app: cassandra-app-cassandra
spec:
  clusterSelector:
    matchLabels:
      environment: Dev
  clusterReplicas: 2
