apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: mortgagepod-placement
  namespace: default
  labels:
    app: mortgagepod
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      environment: Dev

