apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      environment: Dev
  clusterReplicas: 3
