apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: mortgagedc-placement
  namespace: default  
  labels:
    app: mortgagedc
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      environment: Dev
